version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=mykhailo
      - DB_PASSWORD=_pishmak%
      - DB_NAME=weather_database
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - API_PORT=8080
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mykhailo
      POSTGRES_PASSWORD: _pishmak%
      POSTGRES_DB: weather_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge